<h4> Tensors

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cpu
False


<h5> Creating empty tensor

In [3]:
a = torch.empty(2,3)

In [4]:
a.type()

'torch.FloatTensor'

<h5> Create Tensor using zeros

In [6]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

<h5> Using ones

In [8]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

<h5>Using seed </h5>
<p> rand har baar alag value generate karega but if we want same values everytime we choose another method i.e, manual_seed

In [18]:
a = torch.rand(2,2)
a

tensor([[0.5479, 0.4440],
        [0.7041, 0.5573]])

<h5> Using manual seed

In [19]:
a = torch.manual_seed(10)
a = torch.rand(2,3)
a

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

<p> if we want to make a tensor based on our data (we can use tensor)

In [24]:
a = torch.tensor(([1,2,3],[4,5,2]))
a

tensor([[1, 2, 3],
        [4, 5, 2]])

<h5> Other Ways

In [25]:
# using arange 

b = torch.arange(1,10,2)
b


tensor([1, 3, 5, 7, 9])

In [28]:
# using linspace
l = torch.linspace(1,10, 10)
print("10 equally dist between 1 to 10",l)

# jab hum 2 numbers ke beech example 10 equal distance number chahein 
# we can also get 10 equally dist  between 1 to 5

a = torch.linspace(1,5,10)
print("10 equally dist between 1 to 5",a)

10 equally dist between 1 to 10 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
10 equally dist between 1 to 5 tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])


In [29]:
# eye is used for diagonal matrix
a = torch.eye(3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
# full is used to tell the shape of the matrix and which item be filled in that complete matrix

a = torch.full((3,3), 2)
a

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

<h5> Shape

In [31]:
a.shape

torch.Size([3, 3])

<h6> now if we want to give a shape like any of our previous tensor

In [32]:
x = torch.tensor(([1,2,3],[4,5,2]))
x

tensor([[1, 2, 3],
        [4, 5, 2]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

<p> similarly

In [37]:
b =torch.ones_like(x)
b

tensor([[1, 1, 1],
        [1, 1, 1]])

<p> but it will give error if we use exactly with rand because rand gives us float so we need to define the data type first

In [44]:
b =torch.rand_like(x, dtype=torch.float16)
b

tensor([[0.5601, 0.5762, 0.9810],
        [0.3579, 0.7422, 0.9517]], dtype=torch.float16)

<h4> Tensor Data Types

In [38]:
# find type of data
x.dtype

torch.int64

In [39]:
# want to make tensor of int type
t = torch.tensor([[1.2,2]], dtype=int)
t

tensor([[1, 2]])

In [42]:
d = torch.tensor([[1.2,2]], dtype=torch.int32)
d

tensor([[1, 2]], dtype=torch.int32)

In [43]:
d = torch.tensor([[1.2,2]], dtype=torch.float16)
d

tensor([[1.2002, 2.0000]], dtype=torch.float16)

<p> We can change the existing data type of a tensor
<h5> Using to()

In [46]:
d.to(torch.int16)

tensor([[1, 2]], dtype=torch.int16)