<h4> Tensors

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cpu
False


<h5> Creating empty tensor

In [3]:
a = torch.empty(2,3)

In [4]:
a.type()

'torch.FloatTensor'

<h5> Create Tensor using zeros

In [6]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

<h5> Using ones

In [8]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

<h5>Using seed </h5>
<p> rand har baar alag value generate karega but if we want same values everytime we choose another method i.e, manual_seed

In [18]:
a = torch.rand(2,2)
a

tensor([[0.5479, 0.4440],
        [0.7041, 0.5573]])

<h5> Using manual seed

In [19]:
a = torch.manual_seed(10)
a = torch.rand(2,3)
a

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

<p> if we want to make a tensor based on our data (we can use tensor)

In [24]:
a = torch.tensor(([1,2,3],[4,5,2]))
a

tensor([[1, 2, 3],
        [4, 5, 2]])

<h5> Other Ways

In [25]:
# using arange 

b = torch.arange(1,10,2)
b


tensor([1, 3, 5, 7, 9])

In [28]:
# using linspace
l = torch.linspace(1,10, 10)
print("10 equally dist between 1 to 10",l)

# jab hum 2 numbers ke beech example 10 equal distance number chahein 
# we can also get 10 equally dist  between 1 to 5

a = torch.linspace(1,5,10)
print("10 equally dist between 1 to 5",a)

10 equally dist between 1 to 10 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
10 equally dist between 1 to 5 tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])


In [29]:
# eye is used for diagonal matrix
a = torch.eye(3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [30]:
# full is used to tell the shape of the matrix and which item be filled in that complete matrix

a = torch.full((3,3), 2)
a

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

<h5> Shape

In [31]:
a.shape

torch.Size([3, 3])

<h6> now if we want to give a shape like any of our previous tensor

In [32]:
x = torch.tensor(([1,2,3],[4,5,2]))
x

tensor([[1, 2, 3],
        [4, 5, 2]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

<p> similarly

In [37]:
b =torch.ones_like(x)
b

tensor([[1, 1, 1],
        [1, 1, 1]])

<p> but it will give error if we use exactly with rand because rand gives us float so we need to define the data type first

In [44]:
b =torch.rand_like(x, dtype=torch.float16)
b

tensor([[0.5601, 0.5762, 0.9810],
        [0.3579, 0.7422, 0.9517]], dtype=torch.float16)

<h4> Tensor Data Types

In [38]:
# find type of data
x.dtype

torch.int64

In [39]:
# want to make tensor of int type
t = torch.tensor([[1.2,2]], dtype=int)
t

tensor([[1, 2]])

In [42]:
d = torch.tensor([[1.2,2]], dtype=torch.int32)
d

tensor([[1, 2]], dtype=torch.int32)

In [43]:
d = torch.tensor([[1.2,2]], dtype=torch.float16)
d

tensor([[1.2002, 2.0000]], dtype=torch.float16)

<p> We can change the existing data type of a tensor
<h5> Using to()

In [46]:
d.to(torch.int16)

tensor([[1, 2]], dtype=torch.int16)

<h4> Mathematical Operations

In [52]:
#  -----------------------   Scalar Operation     --------------------------------------
t1 = torch.tensor([[1,2,3],[3,2,1]])
print("Before operation: ", t1)
t1 = t1+2
print("After adding 2 in the tensor:  ", t1)

print("Similarly sub, mult, div, modulo")
print(t1-2)

Before operation:  tensor([[1, 2, 3],
        [3, 2, 1]])
After adding 2 in the tensor:   tensor([[3, 4, 5],
        [5, 4, 3]])
Similarly sub, mult, div, modulo
tensor([[1, 2, 3],
        [3, 2, 1]])


In [53]:
print(t1*2)

tensor([[ 6,  8, 10],
        [10,  8,  6]])


In [54]:
print(t1/2)

tensor([[1.5000, 2.0000, 2.5000],
        [2.5000, 2.0000, 1.5000]])


In [55]:
print(t1%2)

tensor([[1, 0, 1],
        [1, 0, 1]])


In [56]:
print(t1**2)

tensor([[ 9, 16, 25],
        [25, 16,  9]])


<h5> Element wise operation

In [60]:
a = torch.manual_seed(100)
a = torch.rand(2,3, dtype=torch.float16)
b = torch.manual_seed(100)
b = torch.rand(2,3, dtype=torch.float16)
print(a)
print(b)

tensor([[0.7539, 0.3867, 0.9077],
        [0.9253, 0.9175, 0.0386]], dtype=torch.float16)
tensor([[0.7539, 0.3867, 0.9077],
        [0.9253, 0.9175, 0.0386]], dtype=torch.float16)


In [61]:
a+b

tensor([[1.5078, 0.7734, 1.8154],
        [1.8506, 1.8350, 0.0771]], dtype=torch.float16)

In [62]:
a-b

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [64]:
a//b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [ ]:
# ------------------absolute--------------------
n = torch.tensor([-1,-2,-2])
torch.abs(n)

tensor([1, 2, 2])

In [69]:
#  ------------------------negative------------------
torch.negative(b)

tensor([[-0.7539, -0.3867, -0.9077],
        [-0.9253, -0.9175, -0.0386]], dtype=torch.float16)

In [70]:
# --------------round -------------
torch.round(b)

tensor([[1., 0., 1.],
        [1., 1., 0.]], dtype=torch.float16)

In [71]:
# -------------------ceil------------------
torch.ceil(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [73]:
# ----------------------------floor---------------
torch.floor(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [ ]:
# --------clamp------------------
torch.clamp(x, max= 4, min =2)

# clamp ka use hota hai same category me laane ke liye, jaise maine set kiya koi number 4 se bda hai toh 3 ho jayega aur 2 se chhota hai toh 2 ho jayega

tensor([[2, 2, 3],
        [4, 4, 2]])

<h4> Reduction Operation

In [82]:
a = torch.manual_seed(10)
a = torch.randint(size=(2,3), low=0, high=5)
a

tensor([[2, 0, 2],
        [2, 2, 0]])

In [83]:
# if we want to get sum of all elements of a tensor
torch.sum(a)

tensor(8)

In [84]:
# if we want to get sum of all elements per column
torch.sum(a, dim=0)


tensor([4, 2, 2])

In [85]:
# if we want to get sum of all elements per row
torch.sum(a, dim=1)


tensor([4, 4])

<p> similarly mean can be calculated but for mean float datatype is a must

<p> similary mode, max, min, std, var , argmin, argmax are also reduction operations

<h2> Matrix Operations

In [87]:
t1 = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Reshaping")
print(t1.reshape(6, 2))

print("\nResizing")
print(t1.view(2, 6))

print("\nTransposing")
print(t1.transpose(0, 1))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [88]:
t2 = torch.tensor([[10, 1, 3, 2],
                 [5, 5, 2, 8],
                 [9, 10, 1, 1]])
t1+t2

tensor([[11,  3,  6,  6],
        [10, 11,  9, 16],
        [18, 20, 12, 13]])

<p>  similary dot, product, subtraction division can be done on matrices 

In [89]:
t1-t2

tensor([[-9,  1,  0,  2],
        [ 0,  1,  5,  0],
        [ 0,  0, 10, 11]])

In [93]:
# matrix multiplication
t1 = torch.tensor([[2,3],[3,2]])
t2 = torch.tensor([[4,3],[1,2]])
torch.matmul(t1,t2)

tensor([[11, 12],
        [14, 13]])

In [97]:
i = torch.tensor([2,3])
j = torch.tensor([4,3])
torch.dot(i,j)

# dot product is only for 1d tensors

tensor(17)

In [108]:
# determinant 
z = torch.tensor([[2.1, 1],[0,1]], dtype=torch.float32)
z

tensor([[2.1000, 1.0000],
        [0.0000, 1.0000]])

In [109]:
torch.det(z)

tensor(2.1000)

In [110]:
torch.inverse(z)

tensor([[ 0.4762, -0.4762],
        [ 0.0000,  1.0000]])

<h4> Comparison Operations