<a href="https://colab.research.google.com/github/varshasharma01/Practice_PyTorch/blob/main/01_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h4> Tensors

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cpu
False


<h5> Creating empty tensor

In [ ]:
a = torch.empty(2,3)

In [ ]:
a.type()

'torch.FloatTensor'

<h5> Create Tensor using zeros

In [ ]:
a = torch.zeros(3,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

<h5> Using ones

In [ ]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

<h5>Using seed </h5>
<p> rand har baar alag value generate karega but if we want same values everytime we choose another method i.e, manual_seed

In [ ]:
a = torch.rand(2,2)
a

tensor([[0.8686, 0.3562],
        [0.0195, 0.6528]])

<h5> Using manual seed

In [ ]:
a = torch.manual_seed(10)
a = torch.rand(2,3)
a

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

<p> if we want to make a tensor based on our data (we can use tensor)

In [ ]:
a = torch.tensor(([1,2,3],[4,5,2]))
a

tensor([[1, 2, 3],
        [4, 5, 2]])

<h5> Other Ways

In [ ]:
# using arange

b = torch.arange(1,10,2)
b


tensor([1, 3, 5, 7, 9])

In [ ]:
# using linspace
l = torch.linspace(1,10, 10)
print("10 equally dist between 1 to 10",l)

# jab hum 2 numbers ke beech example 10 equal distance number chahein
# we can also get 10 equally dist  between 1 to 5

a = torch.linspace(1,5,10)
print("10 equally dist between 1 to 5",a)

10 equally dist between 1 to 10 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
10 equally dist between 1 to 5 tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])


In [ ]:
# eye is used for diagonal matrix
a = torch.eye(3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
# full is used to tell the shape of the matrix and which item be filled in that complete matrix

a = torch.full((3,3), 2)
a

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

<h5> Shape

In [ ]:
a.shape

torch.Size([3, 3])

<h6> now if we want to give a shape like any of our previous tensor

In [ ]:
x = torch.tensor(([1,2,3],[4,5,2]))
x

tensor([[1, 2, 3],
        [4, 5, 2]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

<p> similarly

In [ ]:
b =torch.ones_like(x)
b

tensor([[1, 1, 1],
        [1, 1, 1]])

<p> but it will give error if we use exactly with rand because rand gives us float so we need to define the data type first

In [ ]:
b =torch.rand_like(x, dtype=torch.float16)
b

tensor([[0.5601, 0.5762, 0.9810],
        [0.3579, 0.7422, 0.9517]], dtype=torch.float16)

<h4> Tensor Data Types

In [ ]:
# find type of data
x.dtype

torch.int64

In [ ]:
# want to make tensor of int type
t = torch.tensor([[1.2,2]], dtype=int)
t

tensor([[1, 2]])

In [ ]:
d = torch.tensor([[1.2,2]], dtype=torch.int32)
d

tensor([[1, 2]], dtype=torch.int32)

In [ ]:
d = torch.tensor([[1.2,2]], dtype=torch.float16)
d

tensor([[1.2002, 2.0000]], dtype=torch.float16)

<p> We can change the existing data type of a tensor
<h5> Using to()

In [ ]:
d.to(torch.int16)

tensor([[1, 2]], dtype=torch.int16)

<h4> Mathematical Operations

In [ ]:
#  -----------------------   Scalar Operation     --------------------------------------
t1 = torch.tensor([[1,2,3],[3,2,1]])
print("Before operation: ", t1)
t1 = t1+2
print("After adding 2 in the tensor:  ", t1)

print("Similarly sub, mult, div, modulo")
print(t1-2)

Before operation:  tensor([[1, 2, 3],
        [3, 2, 1]])
After adding 2 in the tensor:   tensor([[3, 4, 5],
        [5, 4, 3]])
Similarly sub, mult, div, modulo
tensor([[1, 2, 3],
        [3, 2, 1]])


In [ ]:
print(t1*2)

tensor([[ 6,  8, 10],
        [10,  8,  6]])


In [ ]:
print(t1/2)

tensor([[1.5000, 2.0000, 2.5000],
        [2.5000, 2.0000, 1.5000]])


In [ ]:
print(t1%2)

tensor([[1, 0, 1],
        [1, 0, 1]])


In [ ]:
print(t1**2)

tensor([[ 9, 16, 25],
        [25, 16,  9]])


<h5> Element wise operation

In [ ]:
a = torch.manual_seed(100)
a = torch.rand(2,3, dtype=torch.float16)
b = torch.manual_seed(100)
b = torch.rand(2,3, dtype=torch.float16)
print(a)
print(b)

tensor([[0.7539, 0.3867, 0.9077],
        [0.9253, 0.9175, 0.0386]], dtype=torch.float16)
tensor([[0.7539, 0.3867, 0.9077],
        [0.9253, 0.9175, 0.0386]], dtype=torch.float16)


In [ ]:
a+b

tensor([[1.5078, 0.7734, 1.8154],
        [1.8506, 1.8350, 0.0771]], dtype=torch.float16)

In [ ]:
a-b

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [ ]:
a//b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [ ]:
# ------------------absolute--------------------
n = torch.tensor([-1,-2,-2])
torch.abs(n)

tensor([1, 2, 2])

In [ ]:
#  ------------------------negative------------------
torch.negative(b)

tensor([[-0.7539, -0.3867, -0.9077],
        [-0.9253, -0.9175, -0.0386]], dtype=torch.float16)

In [ ]:
# --------------round -------------
torch.round(b)

tensor([[1., 0., 1.],
        [1., 1., 0.]], dtype=torch.float16)

In [ ]:
# -------------------ceil------------------
torch.ceil(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [ ]:
# ----------------------------floor---------------
torch.floor(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

In [ ]:
# --------clamp------------------
torch.clamp(x, max= 4, min =2)

# clamp ka use hota hai same category me laane ke liye, jaise maine set kiya koi number 4 se bda hai toh 3 ho jayega aur 2 se chhota hai toh 2 ho jayega

tensor([[2, 2, 3],
        [4, 4, 2]])

<h4> Reduction Operation

In [ ]:
a = torch.manual_seed(10)
a = torch.randint(size=(2,3), low=0, high=5)
a

tensor([[2, 0, 2],
        [2, 2, 0]])

In [ ]:
# if we want to get sum of all elements of a tensor
torch.sum(a)

tensor(8)

In [ ]:
# if we want to get sum of all elements per column
torch.sum(a, dim=0)


tensor([4, 2, 2])

In [ ]:
# if we want to get sum of all elements per row
torch.sum(a, dim=1)


tensor([4, 4])

<p> similarly mean can be calculated but for mean float datatype is a must

<p> similary mode, max, min, std, var , argmin, argmax are also reduction operations

<h2> Matrix Operations

In [ ]:
t1 = torch.tensor([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print("Reshaping")
print(t1.reshape(6, 2))

print("\nResizing")
print(t1.view(2, 6))

print("\nTransposing")
print(t1.transpose(0, 1))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [ ]:
t2 = torch.tensor([[10, 1, 3, 2],
                 [5, 5, 2, 8],
                 [9, 10, 1, 1]])
t1+t2

tensor([[11,  3,  6,  6],
        [10, 11,  9, 16],
        [18, 20, 12, 13]])

<p>  similary dot, product, subtraction division can be done on matrices

In [ ]:
t1-t2

tensor([[-9,  1,  0,  2],
        [ 0,  1,  5,  0],
        [ 0,  0, 10, 11]])

In [ ]:
# matrix multiplication
t1 = torch.tensor([[2,3],[3,2]])
t2 = torch.tensor([[4,3],[1,2]])
torch.matmul(t1,t2)

tensor([[11, 12],
        [14, 13]])

In [ ]:
i = torch.tensor([2,3])
j = torch.tensor([4,3])
torch.dot(i,j)

# dot product is only for 1d tensors

tensor(17)

In [ ]:
# determinant
z = torch.tensor([[2.1, 1],[0,1]], dtype=torch.float32)
z

tensor([[2.1000, 1.0000],
        [0.0000, 1.0000]])

In [ ]:
torch.det(z)

tensor(2.1000)

In [ ]:
torch.inverse(z)

tensor([[ 0.4762, -0.4762],
        [ 0.0000,  1.0000]])

<h4> Comparison Operations

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])

print(a == b)   # Equal
print(a != b)   # Not equal
print(a > b)    # Greater than
print(a < b)    # Less than
print(a >= b)   # Greater than or equal
print(a <= b)   # Less than or equal

tensor([False,  True, False])
tensor([ True, False,  True])
tensor([False, False,  True])
tensor([ True, False, False])
tensor([False,  True,  True])
tensor([ True,  True, False])


<h4> Using torch functions

In [ ]:
torch.eq(a, b)
torch.ne(a, b)
torch.gt(a, b)
torch.lt(a, b)
torch.ge(a, b)
torch.le(a, b)

tensor([ True,  True, False])

<h4> Special functions

In [ ]:
x = torch.tensor([-1.0, 0.0, 1.0])

torch.sigmoid(x)

tensor([0.2689, 0.5000, 0.7311])

In [ ]:
torch.log(x)

tensor([nan, -inf, 0.])

In [ ]:
torch.exp(x)

tensor([0.3679, 1.0000, 2.7183])

In [ ]:
torch.sqrt(x)

tensor([nan, 0., 1.])

In [ ]:
torch.softmax(x, dim =0)

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
torch.relu(x)

tensor([0., 0., 1.])

In [ ]:
torch.tanh(x)

tensor([-0.7616,  0.0000,  0.7616])

<h4> Inplace Operations

In [ ]:
# inplace ka use karte hain jo result aaye woh usi col ya dataset me original value ko replace kar de
# ex: we have a large datset stored in the form of tensors we can  upate a column and store into same column without occupying extra memory

In [ ]:
x = torch.tensor([1, 2, 3])
x.add_(1)   # modifies x itself
# add and underscore with function for permanent changes

print(x)

tensor([2, 3, 4])


<h5> Copy Tensor

In [ ]:
# using assignment operator if we do a = b
# they points toward same memory location and also if a is changed b will be changed that's a problem
a = b

In [ ]:
id(a)

138584193455824

In [ ]:
id(b)

138584193455824

In [ ]:
a

tensor([2, 2, 2])

In [ ]:
b

tensor([2, 2, 2])

In [ ]:
a[0] = 1

In [ ]:
b

tensor([1, 2, 2])

<h5> to solve this use clone

In [ ]:
a = b.clone()

In [ ]:
a,b

(tensor([1, 2, 2]), tensor([1, 2, 2]))

In [ ]:
a[0]=10

In [ ]:
a, b

(tensor([10,  2,  2]), tensor([1, 2, 2]))

In [ ]:
id(a), id(b)

(138584191409744, 138584193455824)

<h5> Tensor Operations on GPU

In [ ]:
print(torch.cuda.is_available())

False


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.tensor([1,2,3], device=device)

tensor([1, 2, 3])

In [ ]:
z = torch.rand(2,3)
z

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

In [ ]:
# the above tensor made on Cpu-----------------------to convert the device use to( device)

z = z.to(device)
z

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

In [ ]:
# let's check the difference between the timings of CPU and GPU
import time

In [ ]:
size = 10000

In [ ]:
cpu_matrix1 = torch.rand(size, size)
cpu_matrix2 = torch.rand(size, size)

In [ ]:
gpu_matrix1 = cpu_matrix1.to(device)
gpu_matrix2 = cpu_matrix2.to(device)

In [ ]:
cpu_matrix1, gpu_matrix1

(tensor([[0.7041, 0.5573, 0.6959,  ..., 0.1091, 0.9881, 0.3696],
         [0.3514, 0.6467, 0.9893,  ..., 0.1045, 0.0081, 0.0496],
         [0.1716, 0.7057, 0.0778,  ..., 0.8494, 0.3192, 0.8282],
         ...,
         [0.0618, 0.0742, 0.2315,  ..., 0.0835, 0.4974, 0.5774],
         [0.2477, 0.3697, 0.8441,  ..., 0.6009, 0.8727, 0.6997],
         [0.7110, 0.4723, 0.5588,  ..., 0.4099, 0.0769, 0.6236]]),
 tensor([[0.7041, 0.5573, 0.6959,  ..., 0.1091, 0.9881, 0.3696],
         [0.3514, 0.6467, 0.9893,  ..., 0.1045, 0.0081, 0.0496],
         [0.1716, 0.7057, 0.0778,  ..., 0.8494, 0.3192, 0.8282],
         ...,
         [0.0618, 0.0742, 0.2315,  ..., 0.0835, 0.4974, 0.5774],
         [0.2477, 0.3697, 0.8441,  ..., 0.6009, 0.8727, 0.6997],
         [0.7110, 0.4723, 0.5588,  ..., 0.4099, 0.0769, 0.6236]]))

In [ ]:
start_time = time.time()
cpu_result = torch.matmul(cpu_matrix1, cpu_matrix2)
total_time = time.time()-start_time
print("CPU time: ", total_time)

CPU time:  34.580486536026


In [ ]:
start_time = time.time()
gpu_result = torch.matmul(gpu_matrix1, gpu_matrix2)
total_time = time.time()-start_time
total_time

32.25299668312073

In [ ]:
w = torch.tensor([[1,2],[2,2]])
w.shape

torch.Size([2, 2])

In [ ]:

w = torch.tensor([1,2])
w

tensor([1, 2])

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
w.dtype

torch.int64

In [ ]:
w =w.to(dtype=torch.float32)
w.dtype

torch.float32


<h5> Reshaping


In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.flatten(a)

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a = torch.eye(3,3)
a

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
a.permute(1,0)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
a = torch.rand(2,3,4)
a

tensor([[[0.7642, 0.5817, 0.2638, 0.8852],
         [0.9186, 0.6990, 0.1491, 0.1460],
         [0.1198, 0.3274, 0.1968, 0.6773]],

        [[0.8070, 0.4816, 0.7481, 0.5403],
         [0.6589, 0.8239, 0.7563, 0.4834],
         [0.6271, 0.1826, 0.6694, 0.9204]]])

In [ ]:
a.permute(2,1,0)

tensor([[[0.7642, 0.8070],
         [0.9186, 0.6589],
         [0.1198, 0.6271]],

        [[0.5817, 0.4816],
         [0.6990, 0.8239],
         [0.3274, 0.1826]],

        [[0.2638, 0.7481],
         [0.1491, 0.7563],
         [0.1968, 0.6694]],

        [[0.8852, 0.5403],
         [0.1460, 0.4834],
         [0.6773, 0.9204]]])

In [ ]:
# unsqueeze  is used to
c = torch.rand(226,226,3)
c

tensor([[[0.7909, 0.3060, 0.3165],
         [0.6653, 0.6258, 0.0340],
         [0.8710, 0.3960, 0.6991],
         ...,
         [0.0619, 0.6293, 0.0741],
         [0.4422, 0.2614, 0.1069],
         [0.0862, 0.2125, 0.8684]],

        [[0.4590, 0.2612, 0.8921],
         [0.1843, 0.9808, 0.5353],
         [0.1029, 0.8059, 0.8672],
         ...,
         [0.0121, 0.8417, 0.1629],
         [0.8808, 0.5772, 0.3423],
         [0.6402, 0.3395, 0.1576]],

        [[0.2809, 0.4870, 0.7111],
         [0.2336, 0.5505, 0.2987],
         [0.2470, 0.6636, 0.3008],
         ...,
         [0.7672, 0.0951, 0.5771],
         [0.0096, 0.5275, 0.1593],
         [0.7669, 0.9720, 0.7607]],

        ...,

        [[0.8930, 0.4882, 0.2033],
         [0.3319, 0.1253, 0.4504],
         [0.3092, 0.0546, 0.2855],
         ...,
         [0.5488, 0.1462, 0.6697],
         [0.3865, 0.6986, 0.3332],
         [0.5991, 0.3445, 0.6551]],

        [[0.2918, 0.4228, 0.6483],
         [0.1539, 0.4242, 0.4644],
         [0.

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])